### PR TITLE
Added fuzzer for oss-fuzz integration.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Hi Maintainers,

I have worked a bit on setting fuzzing up for md4c by way of OSS-Fuzz. https://github.com/google/oss-fuzz/pull/5242 I have done exactly that, namely created the necessary logic from an OSS-Fuzz perspective to integrate md4c. If you would like to integrate, could you please provide a set of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. The emails should be linked to a Google account in order to view the detailed reports and notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

At the moment I stored the fuzzers (in the PR I linked) in the Google OSS-Fuzz repository, but we can move them up here to make maintenance easier.

I noticed that you had previously asked if MD4C is qualified https://github.com/google/oss-fuzz/issues/2134 and I believe following the QT integration it should be ready now!

### CODE REVIEW

**Comment by mity** [comment]
Wonderful. This is great to have.

**Comment by DavidKorczynski** [comment]
Great stuff! Let me know which email you would like to use for the bug reports!

**Comment by mity** [comment]
> If you would like to integrate, could you please provide a set of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

I have no dedicated per-project e-mail addresses, so `martin.mitas@morous.org` would do. (I believe it should not be a problem to change later if needed, right?)

**Comment by DavidKorczynski** [comment]
Awesome! Yeah, it's no problem at all to change it.

**Comment by mity** [comment]
(Just FYI, started to receive mail notifications from it (cool), but I cannot get to the detailed reports, I believe due this bug: https://github.com/google/oss-fuzz/issues/4809)

**Comment by DavidKorczynski** [comment]
Ah - that looks annoying. Am not entirely sure what to do about this, but probably the best is to follow up on the OSS-Fuzz issue.

**Pull request merged**
